name: mobius_custom_linter_report
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  analyzer:
  analyzer_plugin:
  custom_lint: 0.7.0
  custom_lint_builder: 0.7.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
